spring:
  application:
    name: g-52-shop
  datasource:
    url: jdbc:mysql://localhost:3306/g_52_shop
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 111
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

key:
  access: 6j617Y+miGdw5aSpt2e9legY0DhFeK8sOsF22Zfw7FY=
  refresh: yYcZFbfm0yQ/fbviM2IYMbVSvH6f8IQLM5vENuxXrDQ=